runtime: nodejs16
service: hydrogen

handlers:
  - url: /
    secure: always
    static_files: dist/hydrogen-atom/index.html
    upload: dist/hydrogen-atom/index.html

  #  Routing rules for resources, css, js, images etc. Any file with format filename.ext
  - url: /(.*\.(.+))$
    secure: always
    static_files: dist/hydrogen-atom/\1
    upload: dist/hydrogen-atom/(.*\.(.+))$

  #  Routing rule for Angular Routing
  - url: /(.*)
    secure: always
    static_files: dist/hydrogen-atom/index.html
    upload: dist/hydrogen-atom/index.html